# Generated by Django 3.1.3 on 2020-12-05 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coffee_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('I_coffeerate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('I_rate_in_INR', models.DecimalField(decimal_places=4, max_digits=5)),
                ('I_customduty_charges', models.DecimalField(decimal_places=4, max_digits=5)),
                ('I_total_charges', models.DecimalField(decimal_places=4, max_digits=5)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeBrowser.country')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeBrowser.types')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_coffeerate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('E_rate_in_INR', models.DecimalField(decimal_places=4, max_digits=5)),
                ('E_IGST', models.DecimalField(decimal_places=4, max_digits=5)),
                ('E_shipping_charges', models.DecimalField(decimal_places=4, max_digits=5)),
                ('E_total_charges', models.DecimalField(decimal_places=4, max_digits=5)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeBrowser.country')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoffeeBrowser.types')),
            ],
        ),
    ]
