# Generated by Django 3.1.3 on 2020-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeBrowser', '0002_auto_20201205_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('option_one', models.CharField(max_length=25)),
                ('option_two', models.CharField(max_length=25)),
                ('option_three', models.CharField(max_length=25)),
                ('option_four', models.CharField(max_length=25)),
                ('option_one_count', models.IntegerField(default=0)),
                ('option_two_count', models.IntegerField(default=0)),
                ('option_three_count', models.IntegerField(default=0)),
                ('option_four_count', models.IntegerField(default=0)),
            ],
        ),
    ]
